### ISSUE TITLE
Recently fail to conect to any API node

### ISSUE THREAD

**Issue by mostar** [PBSA/python-peerplays#12]
I'm using code that base on this python-peerplays library for a few month successfully.
Recently it fail to to connect to the api node, try several from:
https://peerplays.atlassian.net/wiki/spaces/PD/pages/15564866/Witness+Node+Connection+Details

Getting this message:

> Lost connection to node during wsconnect(): wss://peerplays-dev.blocktrades.info/ws (2/-1) Retrying in 2 seconds

I change in storage.py to the new default node:
 "node": "ws://ec2-35-183-21-190.ca-central-1.compute.amazonaws.com:8090",
 and now I'm getting 

> Lost connection to node during wsconnect(): ws://ec2-35-183-21-190.ca-central-1.compute.amazonaws.com:8090 (2/-1) Retrying in 2 seconds

Why it use the default node and not the one in my code ?
Is the default node offline ?

**Comment by xeroc** [comment]
There is actually no real *default* node .. the software so far is meant for witness operators who should have an api node at hand ..
it can be changed using

    peerplays set node ws://.....
